### ISSUE TITLE
Feature request: `Database` item category

### ISSUE THREAD

**Issue by sondrelg** [bsodmike/connect-sdk-rust#3]
Hi @bsodmike!

This library looks very useful, thanks for creating it! 

I'm looking to fetch database credentials. Would it be possible to implement the `Database` item category, or is there an existing way for me to retrieve credentials that I've missed?

**Comment by bsodmike** [comment]
Hi @sondrelg thanks for the kind comments. Been a while since I looked at this. Let me update you when I have time to extend the API. 

Feel free to may be sponsor my opensource contributions if you have found them useful please. Every little bit of support helps ❤️

Best M

**Comment by sondrelg** [comment]
Thanks for the quick response @bsodmike! After mulling it over a bit, I think calling the `op` CLI directly will work well enough for my simple use-case, so since there doesn't seem to otherwise be much demand for this, I think it's okay to forget about it. Sorry about that!
